title: gaga's blog
name: gaga's blog
description: Thoughts and experiments

remote_theme: andrewhwanpark/brutalist-blog 

# A short description (e.g., A blog dedicated to reviewing cat gifs), used as part of the title tag like Ben's Awesome Site | A blog dedicated to reviewing cat gifs instead of Ben's Awesome Site | Long description about a blog dedicated to reviewing cat gifs that would be used when page.title is not defined.
tagline: Minimalistic Jekyll theme that automatically supports dark and light modes for blogs

# A longer description used for the description meta tag. Also used as fallback for pages that don't provide their own description, and also as part of the page's title tag if neither page.title nor site.tagline has been defined.
description: Minimalistic Jekyll theme that automatically supports dark and light modes for blogs

# The full URL to your site. Note: site.github.url will be used by default.
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# global author information
author: rhythmic1234

permalink: /:year/:month/:day/:title/

# Includes an icon in the footer for each username you enter
footer-links:
  email: 
  github:  
  linkedin: 

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
