title: gaga's blog
description: Thoughts and experiments

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "blog.md"}

remote_theme: brutalist-blog

plugins:
  - jemoji
