title: gaga's blog
name: gaga's blog
description: Thoughts and experiments

remote_theme: andrewhwanpark/brutalist-blog

# The full URL to your site. Note: site.github.url will be used by default.
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# global author information
author: rhythmic1234

permalink: /:year/:month/:day/:title/

# Includes an icon in the footer for each username you enter
footer-links:
  email: 
  github:  
  linkedin: 

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
